FROM argussdr/sdr-tdoa-df:dev-0.4
ENV TZ=America/Chicago

WORKDIR /SDR-TDOA-DF
COPY nice_data/ nice_data/
COPY GRC/ GRC/
COPY Inventory.md README.md sdr_device_manager.py tdoa_processor_three_stations.py LICENSE sync_collect_samples.py NOTES.md TDOA_Direction_Finding_Guide.md ./

RUN pip install -r requirements.txt
